// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SOFENGG_Order_Request_Document.View.Order {
	
	
	public partial class InfoMailDe {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.HyperLink hlPersonal;
		
		protected System.Web.UI.WebControls.HyperLink hlAcademic;
		
		protected System.Web.UI.WebControls.TextBox txtMailAddress;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvMailAddress;
		
		protected System.Web.UI.WebControls.TextBox txtZipCode;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvZipCode;
		
		protected System.Web.UI.WebControls.DropDownList ddlDelivery;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvDelivery;
		
		protected System.Web.UI.WebControls.TextBox txtMailingNum;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvMailingNum;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
