// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SOFENGG_Order_Request_Document.View.Order {
	
	
	public partial class InfoAcadDe {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.HyperLink hlPersonal;
		
		protected System.Web.UI.WebControls.DropDownList ddlCampus;
		
		protected System.Web.UI.WebControls.DropDownList ddlYearAdmitted;
		
		protected System.Web.UI.WebControls.DropDownList ddlDegree;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvDegree;
		
		protected System.Web.UI.WebControls.TextBox txtStudNo;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rexStudNo;
		
		protected System.Web.UI.WebControls.RadioButtonList optAdmittedAs;
		
		protected System.Web.UI.WebControls.LinkButton btnSubmitStudentDegree;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
