// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SOFENGG_Order_Request_Document.View.Order {
	
	
	public partial class PersonalInformation {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtLName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvLName;
		
		protected System.Web.UI.WebControls.TextBox txtFName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvFName;
		
		protected System.Web.UI.WebControls.TextBox txtMName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvMName;
		
		protected System.Web.UI.WebControls.RadioButtonList optGender;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvGender;
		
		protected System.Web.UI.WebControls.DropDownList ddlBirthMonth;
		
		protected System.Web.UI.WebControls.DropDownList ddlBirthDay;
		
		protected System.Web.UI.WebControls.DropDownList ddlBirthYear;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvBirthYear;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvBirthMonth;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvBirthDay;
		
		protected System.Web.UI.WebControls.TextBox txtCitizen;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvCitizen;
		
		protected System.Web.UI.WebControls.TextBox txtCurrentAddress;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvCurrentAddress;
		
		protected System.Web.UI.WebControls.TextBox txtPhoneNum;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rexPhoneNum;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPhoneNum;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rexEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
		
		protected System.Web.UI.WebControls.TextBox txtHSAttended;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvHSAttended;
		
		protected System.Web.UI.WebControls.TextBox txtBirthplace;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvBirthplace;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
